config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: { subdomain: 'www' }

  resource :design, only: %i[new create show]

  get 'images/adjust', to: 'images#adjust', as: :image_adjust, defaults: { design: 'supreme' }
  get 'images/mockups/t-shirt/:color/*text.:format', to: 'images#mockup', as: :mockup_image, defaults: { design: 'supreme', color: 'black', format: 'jpg' }
  get 'images/printfiles/:printfile_id/:design/*text.:format', to: 'images#printfile', as: :printfile_image, defaults: { design: 'supreme', format: 'png' }
  get 'images/:design(/x:size)/*text.:format', to: 'images#show', as: :generated_image, defaults: { design: 'supreme', format: 'png' }

  get 'cart', to: 'cart#show'
  post 'cart/update', to: 'cart#update', as: :update_cart
  post 'cart/add', to: 'cart#add', as: :add_to_cart
  post 'cart/remove', to: 'cart#remove', as: :remove_from_cart

  get 'checkout', to: 'orders#new', as: :checkout
  get 'checkout/pay', to: 'orders#pay', as: :checkout_pay
  resources :orders, only: [:create]

  post 'charges', to: 'orders#charge'
  get 'countries/states', to: 'countries#states', as: :country_states

  get 'words/fake', to: 'words#fake'
  get 'words/related', to: 'words#related'
end

app/controllers/designs_controller.rb
# frozen_string_literal: true

class DesignsController < ApplicationController
  include NormalizeText

  def new
    @text = normalized_text
    puts "text is #{@text}"
  end

  def create
    redirect_to design_path(text: normalized_text)
  end

  def show
    @text = normalized_text

    redirect_to(design_path(text: 'Supermeme')) && return if @text.blank?
    redirect_to(design_path(text: @text.slice(0, 24))) && return if @text.length > 24

    selected_color = params.fetch('color', 'Black')
    selected_size = params.fetch('size', 'M')

    @design = 'supreme'
    @design_title = "#{@design.capitalize} style #{@text}"

    @product = Product.first
    @product_title = "#{@design.capitalize} style #{@product.title}"

    variants = @product.variants
    @variant = variants.where(color: selected_color, size: selected_size).first || variants.first
    @variant_title = "#{selected_color} #{@product_title} with \"#{@text}\""

    @image_url = generated_image_url(@text, design: @design, size: 144)
    @mockup_url = mockup_image_url(@text, color: selected_color.parameterize)

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/designs_helper.rb
# frozen_string_literal: true

module DesignsHelper
  def color_options_for_select(product, variant)
    available_colors = product.variants.pluck(:color).uniq
    selected_color = variant.color
    options_for_select(available_colors, selected_color)
  end

  def size_options_for_select(product, variant)
    available_sizes = product.variants.pluck(:size).uniq
    selected_size = variant.size
    options_for_select(available_sizes, selected_size)
  end
end

app/views/designs/_form.html.erb
<%= form_tag(add_to_cart_path) do %>
  <%= hidden_field_tag(:text, text) %>
  <div class="form-row">
    <div class="col">
      <div class="form-group">
        <%= label_tag(:size, "Size") %>
        <%= select_tag(:size, size_options_for_select(product, variant), { class: "form-control" }) %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= label_tag(:color, "Color") %>
        <%= select_tag(:color, color_options_for_select(product, variant), { class: "form-control" }) %>
      </div>
    </div>
  </div>
  <%= submit_tag("Buy now", class: "btn btn-lg btn-animated btn-supreme") %>
<% end %>
<script type='text/javascript'>
  $("select[name='color']").change(function () {
    var color = $(this).val();
    $.ajax({
      url: '<%= design_path(text: text) %>',
      type: 'get',
      data: { color: color },
      dataType: 'script',
    });
  });
</script>

app/views/designs/new.html.erb
<% title "Create your design" %>
<% description "Write something awesome and see your design in the iconic Supreme box logo style." %>
<% set_meta_tags og: {
  image: {
    _: asset_url("mockup-generator.jpg"),
    alt: "Supreme style white t-shirt with \"Rosebud.\""
  }
} %>

<div class="container">
  <p class="small text-center step">Step 1 of 4</p>
  <h1 class="page-title">Create your design</h1>
  <div class="row">
    <div class="col-md-8 col-lg-6 mx-auto">
    <div class="card p-3">
    <%= react_component("DesignForm", { action: design_path, initialText: @text }) %>
    </div></div>
  </div>
  <div id="fake-designs">
    <%= react_component("FakeDesigns", { count: 25 }) %>
  </div>
</div>

app/views/designs/show.html.erb
<% title "\"#{@text}\" #{@product_title}" %>
<% description "Custom \"#{@text}\" #{@product_title} in the iconic Supreme box logo style." %>
<% set_meta_tags og: {
  image: {
    _: @mockup_url,
    alt: @variant_title
  }
} %>

<div class="container">
  <p class="small text-center step">Step 2 of 4</p>
  <h1 class="page-title">Choose your size and T-shirt color</h1>
  <div class="row">
    <div class="col-md-6" id="preview-image">
      <%= image_tag @mockup_url, alt: @variant_title %>
    </div>
    <div class="col-md-6" id="customise-design">
      <p><%= image_tag @image_url, alt: @design_title %></p>

      <div class="description">
        <h2><%= @product_title %></h2>
        <div class="price">
          <%= number_to_currency(@variant.price) %>
        </div>
      </div>
      <div id="variant-form">
        <%= render "designs/form", text: @text, product: @product, variant: @variant %>
      </div>

      <div class="text-center text-muted">
        <p>Secure checkout with</p>
        <%= render "trust_signals" %>
      </div>

      <p class="text-center"><%= link_to "Change design", new_design_path(text: @text) %></p>

    </div>

    </div>
<hr class="divider my-5">
      <div class="row my-3">
        <div class="col-md-6">
          <h3>Product description</h3>
          <%= html_description(@product) %>
        </div>
        <div class="col-md-6">
        <div class="size-guide">
          <h3>Size guide</h3>
          <%= render "size_chart" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/designs/show.js.erb
$("#preview-image").html("<%= escape_javascript(image_tag @mockup_url, alt: @variant_title) %>");