config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: { subdomain: 'www' }

  resource :design, only: %i[new create show]

  get 'images/adjust', to: 'images#adjust', as: :image_adjust, defaults: { design: 'supreme' }
  get 'images/mockups/t-shirt/:color/*text.:format', to: 'images#mockup', as: :mockup_image, defaults: { design: 'supreme', color: 'black', format: 'jpg' }
  get 'images/printfiles/:printfile_id/:design/*text.:format', to: 'images#printfile', as: :printfile_image, defaults: { design: 'supreme', format: 'png' }
  get 'images/:design(/x:size)/*text.:format', to: 'images#show', as: :generated_image, defaults: { design: 'supreme', format: 'png' }

  get 'cart', to: 'cart#show'
  post 'cart/update', to: 'cart#update', as: :update_cart
  post 'cart/add', to: 'cart#add', as: :add_to_cart
  post 'cart/remove', to: 'cart#remove', as: :remove_from_cart

  get 'checkout', to: 'orders#new', as: :checkout
  get 'checkout/pay', to: 'orders#pay', as: :checkout_pay
  resources :orders, only: [:create]

  post 'charges', to: 'orders#charge'
  get 'countries/states', to: 'countries#states', as: :country_states

  get 'words/fake', to: 'words#fake'
  get 'words/related', to: 'words#related'
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  def add
    product = Product.first

    color = params.fetch(:color)
    size = params.fetch(:size)
    text = params.fetch(:text)

    variant = product.variants.where(color: color, size: size).first
    generator = "supreme"

    order = cart

    if order.new_record?
      country_code = request.location.country_code
      order.address = Address.new(country_code: country_code) if country_code.present?
      order.save(validate: false)
    end

    existing_item = order.line_items.where(variant: variant, text: text, generator: generator).first

    if existing_item
      existing_item.quantity += 1
      existing_item.save
    else
      new_item = LineItem.new(
        variant: variant,
        text: text,
        generator: generator,
        quantity: 1
      )
      order.line_items << new_item
    end
    session[:cart_id] = order.id

    redirect_to action: :show
  end

  def remove
    line_item = cart.line_items.find_by(id: params[:line_item_id])
    line_item.destroy if line_item

    respond_to do |format|
      format.html { redirect_to action: :show }
      format.js { render :update }
    end
  end

  def update
    line_item = cart.line_items.find_by(id: params[:line_item_id])
    quantity = params[:quantity].to_i

    line_item.update(quantity: quantity) if line_item && quantity.positive?

    respond_to do |format|
      format.html { redirect_to action: :show }
      format.js { render :update }
    end
  end

  def show
  end
end

app/views/cart/_form.html.erb
<div class="table-responsive">
  <table class="cart table table-sm">
    <thead>
      <tr>
        <th>Item</th>
        <th>Quantity</th>
        <th>
          <div class="text-right">Price</div>
        </th>
      </tr>
    </thead>
    <tbody>
      <% cart.line_items.each do |item| %>
        <tr>
          <td>
            <div class="row">
              <div class="col-sm-4 image">
                <div class="text-center">
                  <%= link_to image_tag(mockup_image_path(item.text, color: item.variant.color.parameterize, width: 128), alt: "#{item.variant.color} T-Shirt with \"#{item.text}\""), design_path(text: item.text) %>
                  <br />
                  <%= link_to image_tag(generated_image_path(item.text, size: 16), alt: item.text), design_path(text: item.text) %>
                </div>
              </div>
              <div class="col-sm-8 d-sm-flex align-items-center description">
                <div>
                  <p><%= item.title %></p>
                  <div class="small text-muted">
                    <%= link_to "Remove", remove_from_cart_path(line_item_id: item.id), remote: true, method: :post, data: { confirm: "Remove from cart?" } %>
                  </div>
                </div>
              </div>
            </div>
          </td>
          <td>
            <%= form_tag(update_cart_path, remote: true, authenticity_token: true) do %>
              <%= hidden_field_tag :line_item_id, item.id %>
              <%= number_field_tag :quantity, item.quantity, min: 1, onchange: "Rails.fire(this.form, 'submit')", class: "form-control" %>
            <% end %>
          </td>
          <td>
            <div class="text-right">
              <%= number_to_currency(item.price) %>
            </div>
          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2">
          Subtotal
        </td>
        <td>
          <div class="text-right">
            <%= number_to_currency(cart.subtotal) %>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          Shipping fee
        </td>
        <td>
          <div class="text-right">
            <%= number_to_currency(cart.shipping_fee) %>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <strong>Total</strong>
        </td>
        <td>
          <div class="text-right">
            <strong><%= number_to_currency(cart.total) %></strong>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/cart/show.html.erb
<% title "Cart" %>

<div class="container">
  <p class="small text-center step">Step 3 of 4</p>
  <h1 class="page-title">Review your shopping cart</h1>
  <% if cart.empty? %>
    <div class="alert alert-warning" role="alert">
      Your Shopping Cart is empty.
    </div>
    <%= link_to "Create a design", new_design_path, class: "btn btn-supreme"%>
  <% else %>
    <div id="cart-form">
      <%= render "cart/form", cart: cart %>
    </div>

    <hr />

    <div class="row justify-content-end">
      <div class="col-md-4 col-lg-2">
        <%= link_to "Checkout", checkout_path, class: 'btn btn-lg btn-supreme btn-block' %>
      </div>
    </div>
  <% end %>
</div>

app/views/cart/update.js.erb
<% if cart.empty? %>
  var cartPath = "<%= cart_path %>";
  document.location.href = cartPath;
<% else %>
  $("#cart-form").html("<%= escape_javascript(render "cart/form", cart: cart) %>");
<% end %>