config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: { subdomain: 'www' }

  resource :design, only: %i[new create show]

  get 'images/adjust', to: 'images#adjust', as: :image_adjust, defaults: { design: 'supreme' }
  get 'images/mockups/t-shirt/:color/*text.:format', to: 'images#mockup', as: :mockup_image, defaults: { design: 'supreme', color: 'black', format: 'jpg' }
  get 'images/printfiles/:printfile_id/:design/*text.:format', to: 'images#printfile', as: :printfile_image, defaults: { design: 'supreme', format: 'png' }
  get 'images/:design(/x:size)/*text.:format', to: 'images#show', as: :generated_image, defaults: { design: 'supreme', format: 'png' }

  get 'cart', to: 'cart#show'
  post 'cart/update', to: 'cart#update', as: :update_cart
  post 'cart/add', to: 'cart#add', as: :add_to_cart
  post 'cart/remove', to: 'cart#remove', as: :remove_from_cart

  get 'checkout', to: 'orders#new', as: :checkout
  get 'checkout/pay', to: 'orders#pay', as: :checkout_pay
  resources :orders, only: [:create]

  post 'charges', to: 'orders#charge'
  get 'countries/states', to: 'countries#states', as: :country_states

  get 'words/fake', to: 'words#fake'
  get 'words/related', to: 'words#related'
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :noindex

  def new
    redirect_to root_url if cart.empty?

    @order = cart.dup

    @address = @order.address || Address.new

    flash[:fulfillment_errors]&.each do |err|
      @order.errors.add(:base, err)
    end

    if flash[:validate]
      @order.validate
      @address.validate
    end
  end

  def create
    order = cart

    if order.update(order_params)
      ok_for_fulfiller = Fulfillment::ValidateOrder.new(order).call
      if ok_for_fulfiller
        redirect_to action: :pay
      else
        flash[:fulfillment_errors] = order.errors[:base]
        redirect_to action: :new
      end
    else
      order.save(validate: false)
      flash[:validate] = true
      redirect_to action: :new
    end
  end

  def pay
    @order = cart
  end

  def charge
    @order = PurchaseOrder.find(params[:order_id])

    # create stripe charge
    Stripe::CreateCharge.new(@order).call(params[:stripeToken])

    @order.update(status: 'paid')

    # send order to fulfiller
    create_order = Fulfillment::CreateOrder.new(@order)
    fulfillment_id = create_order.call(confirm: Rails.configuration.fulfillment[:confirm_order])
    @order.update(fulfiller: create_order.fulfiller, fulfillment_id: fulfillment_id)

    # clear cart
    session[:cart_id] = nil

    # send order confirmation email
    OrderMailer.with(order: @order).order_confirmation.deliver_later

    render :show
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to checkout_pay_path
  end

  def show
    @order = PurchaseOrder.find(params[:id])
  end

  private

  def order_params
    params.require(:purchase_order).permit(:first_name, :last_name, :email, address_attributes: [:street1, :street2, :city, :state, :zip_code, :state_code, :country_code])
  end
end

app/views/orders/_form.html.erb
<%= simple_form_for(order, url: orders_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <div class="row">
      <%= f.input :first_name, wrapper_html: { class: "col" } %>
      <%= f.input :last_name, wrapper_html: { class: "col" } %>
    </div>
    <%= f.input :email, required: true %>
    <%= f.fields_for(:address, address) do |af| %>
      <%= af.input :street1 %>
      <%= af.input :street2 %>
      <%= af.input :country_code, required: true, collection: Countries.list.invert %>
      <%= af.input :state_code, required: true, collection: Countries.states_for(address.country_code).invert %>
      <div class="row">
        <%= af.input :zip_code, wrapper_html: { class: "col" } %>
        <%= af.input :city, wrapper_html: { class: "col" } %>
      </div>
    <% end %>
  </div>
  <div class="form-actions row justify-content-end">
    <div class="col-md-4 col-lg-2">
      <%= f.button :submit, "Continue", class: "btn btn-lg btn-supreme btn-block" %>
    </div>
  </div>
<% end %>
<script type='text/javascript'>
  $("select").select2({
      theme: "bootstrap"
  });
  countryStateSelect(
    "select[name='purchase_order[address_attributes][country_code]']",
    "select[name='purchase_order[address_attributes][state_code]']",
    ".purchase_order_address_state_code"
  );
</script>

app/views/orders/_line_items.html.erb
<% order.line_items.each do |item| %>
  <div class="row">
    <div class="col-4">
      <div class="text-center">
        <br />
        <%= image_tag(generated_image_url(item.text, size: 16), alt: item.text) %>
      </div>
    </div>
    <div class="col-8">
      <div class="text-right">
        <strong><%= number_to_currency(item.price) %></strong>
      </div>
      <p class="text-right small">
        <%= item.variant.product.title %>
        <strong><%= item.variant.color %> <%= item.variant.size %></strong>
        <br />
        x <%= item.quantity %>
      </p>
    </div>
  </div>
<% end %>

app/views/orders/_summary.html.erb
<div>
  <p>
    <%= order.name %>
    <br />
    <%= order.email %>
  </p>
  <p>
    <%= render "shared/address", address: order.address %>
  </p>
</div>
<hr />
<%= render "orders/line_items", order: order %>
<hr />
<div class="row">
  <div class="col-8">
    <p>Subtotal</p>
  </div>
  <div class="col-4">
    <p class="text-right">
      <strong><%= number_to_currency(order.subtotal) %></strong>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-8">
    <p>Shipping fee</p>
  </div>
  <div class="col-4">
    <p class="text-right">
      <strong><%= number_to_currency(order.shipping_fee) %></strong>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-8">
    <p>Total</p>
  </div>
  <div class="col-4">
    <p class="text-right">
      <strong><%= number_to_currency(order.total) %></strong>
    </p>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container">
<p class="small text-center step">Step 4 of 4</p>
  <h1 class="page-title">Enter your shipping details</h1>  
  <%= render "orders/form", order: @order, address: @address %>
</div>

app/views/orders/pay.html.erb
<div class="container">
  <h1 class="page-title">Order summary</h1>
  <div class="card">
    <div class="card-body">
      <div class="card-text">
        <%= render "orders/summary", order: cart %>
      </div>
    </div>
  </div>

  <br />

  <%= form_tag charges_path do %>
    <% if flash[:error].present? %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% end %>

    <%= hidden_field_tag(:order_id, @order.id) %>

    <div class="text-muted">
      <%= render "trust_signals" %>
    </div>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Supermeme"
            data-amount="<%= @order.total_in_cents %>"
            data-email="<%= @order.email %>"
            data-allow-remember-me="false"
            data-locale="auto"></script>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h1 class="page-title">Thank you for your order</h1>
  <%= render "orders/summary", order: @order %>
</div>